// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVutR13I58yvzsHjV5ZLtS9pHfe4cLsJ8',
    appId: '1:626963970726:web:b87ea452393d72655a1267',
    messagingSenderId: '626963970726',
    projectId: 'turbo-16770',
    authDomain: 'turbo-16770.firebaseapp.com',
    storageBucket: 'turbo-16770.firebasestorage.app',
    measurementId: 'G-E872L0BE36',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0VnO4AEfcS_NbCYMHR9KBZOn6UWEFynM',
    appId: '1:626963970726:android:9df9c6d393f51a155a1267',
    messagingSenderId: '626963970726',
    projectId: 'turbo-16770',
    storageBucket: 'turbo-16770.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxWmQAmpbY7yZO4KHk6rPYbZuNmohtv6o',
    appId: '1:626963970726:ios:c26790dbacdf940a5a1267',
    messagingSenderId: '626963970726',
    projectId: 'turbo-16770',
    storageBucket: 'turbo-16770.firebasestorage.app',
    iosBundleId: 'com.example.turbo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxWmQAmpbY7yZO4KHk6rPYbZuNmohtv6o',
    appId: '1:626963970726:ios:c26790dbacdf940a5a1267',
    messagingSenderId: '626963970726',
    projectId: 'turbo-16770',
    storageBucket: 'turbo-16770.firebasestorage.app',
    iosBundleId: 'com.example.turbo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVutR13I58yvzsHjV5ZLtS9pHfe4cLsJ8',
    appId: '1:626963970726:web:5cb3ab712a732fff5a1267',
    messagingSenderId: '626963970726',
    projectId: 'turbo-16770',
    authDomain: 'turbo-16770.firebaseapp.com',
    storageBucket: 'turbo-16770.firebasestorage.app',
    measurementId: 'G-NFY4F5CDRT',
  );

}